import { Metadata } from 'next'
import { Lexend } from 'next/font/google'

import './globals.css'
import FooterMenu from '@/components/Footer'
import { cn } from '@/lib/utils'

const inter = Lexend({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    // useEffect(() => {
    //     const validateHash = async () => {
    //         const res = await fetch('/api/validate-hash', {
    //             method: 'POST',
    //             headers: {
    //                 'Content-Type': 'application/json',
    //             },
    //             body: JSON.stringify({ hash: window.Telegram.WebApp.initData }),
    //         })
    //         const data = await res.json()
    //         console.log({ data })
    //     }

    //     validateHash()
    // }, [])

    return (
        <html lang="en">
            <head>
                <script async src="https://telegram.org/js/telegram-web-app.js" />
            </head>
            <body className={cn(inter.className, 'min-h-screen grainy antialiased')}>
                {children}

                <FooterMenu />
            </body>
        </html>
    )
}
